

class TestCheckout(): 
    def test_checkout_singles(): 
        ...
    def test_checkout_invalid():
        ...
    def test_checkout_deals(): 
        ... 
    def test_checkout_specials():
        ...
    def test_checkout_specials_and_deals(): 
        ... 